---
- hosts: wordpress_host
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mariadb-server
        - php
        - php-mysql

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: true

    - name: Set ownership and permissions
      file:
        path: "/var/www/html/"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Create index.html for verification
      copy:
        content: "WordPress installed successfully!"
        dest: "/var/www/html/index.html"

    - name: Install required PHP extensions
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
        - php-xml

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart MariaDB
      service:
        name: mysql
        state: restarted
