---
- hosts: wordpress_host
  become: true
  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - mariadb-server
        - php
        - php-mysql

    - name: Download and extract WordPress
      get_url:
        url: "https://wordpress.org/latest.tar.gz"
        dest: "/tmp/wordpress.tar.gz"

    - name: Extract WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/html/"
        remote_src: true

    - name: Set ownership and permissions
      file:
        path: "/var/www/html/"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: Configure WordPress
      template:
        src: "wp-config.php.j2"
        dest: "/var/www/html/wp-config.php"
