- hosts: localhost
  become: true
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Install net-tools
      apt:
        name: net-tools
        state: present

    - name: Install munin
      apt:
        name: munin
        state: present

    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Copy apache24.conf.j2 to /etc/munin/
      copy:
        src: "apache24.conf.j2"
        dest: "/etc/munin/apache24.conf"
        owner: root
        group: root
        mode: 0644
      notify: Restart Apache

    - name: Copy munin.conf.j2 to /etc/munin/
      copy:
        src: "munin.conf.j2"
        dest: "/etc/munin/munin.conf"
        owner: root
        group: root
        mode: 0644
      notify: Restart Munin

    - name: Install syslog-ng
      apt:
        name: syslog-ng
        state: present
      become: true

    - name: Copy syslog-ng.conf.j2 to /etc/syslog-ng/
      copy:
        src: "syslog-ng.conf.j2"
        dest: "/etc/syslog-ng/syslog-ng.conf"
        owner: root
        group: root
        mode: 0644
      notify: Restart syslog-ng

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

    - name: Restart Munin
      service:
        name: munin
        state: restarted

    - name: Restart syslog-ng
      service:
        name: syslog-ng
        state: restarted
